### PR TITLE
Rename Dynamo_Toolkit -> Dynamo_UI

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Related to
https://github.com/BHoM/Excel_UI/pull/348

### CODE REVIEW

**Review by alelom — APPROVED** [review]
Approved based on code changes review only.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 7183591660

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 7183768827

**Pull request merged**
